"""empty message

Revision ID: add_flags
Revises: fix_relational
Create Date: 2019-10-17 09:20:34.189145

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'add_flags'
down_revision = 'fix_relational'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_anode():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_flag_documents',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('document_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'document_id')
                    )
    # ### end Alembic commands ###


def downgrade_anode():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_flag_documents')
    # ### end Alembic commands ###
